Added CI config file.
catie-aq/zephyr_zest-core-stm32l562ve pull request #18
Opened 2024-11-26 15:59 UTC by Sokario

2024-11-27 07:40 UTC, clementlgl requested changes
The [github action file](https://github.com/catie-aq/cookiecutter_zephyr/blob/34-add-ci-to-templates/core/%7B%7Bcookiecutter.project_slug%7D%7D/.github/workflows/board.yaml) should be added

2024-11-28 08:49 UTC, Sokario commented on .github/workflows/board.yaml
> +name: "Zephyr Zest_Core_STM32L562VE CI/CD"
Resolved in [5ca4171](https://github.com/catie-aq/zephyr_zest-core-stm32l562ve/pull/18/commits/5ca4171d01864681dc5586ca19748a5e9ae55c1e).

2024-11-28 09:56 UTC, clementlgl approved these changes

2024-11-28 10:00 UTC, bperraudin approved these changes

2024-11-28 10:00 UTC, merged